import Web3AuthWrapper from '@/components/Web3AuthWrapper';
import Providers from '@/web3auth/Providers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Get Fit',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Web3AuthWrapper>
                        {children}
                    </Web3AuthWrapper>
                </Providers>
            </body>
        </html>
    );
}
